version: "3.8"

services:
  localstack:
    hostname: localstack
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - REGION=eu-west-1
      # - DEBUG=true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
