AWSTemplateFormatVersion: 2010-09-09
Description: S3 resources
Parameters:
  Environment:
    Type: String

  Application:
    Type: String

  Version:
    Type: String

  UniqueId:
    Type: String

Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Environment}-${Application}-${UniqueId}-v${Version}
